version: '3.8'

services:
  backend:
    build: . # Build the backend image from the Dockerfile
    ports:
      - "3000:3000" # Map port 3000 of the container to port 3000 of the host
    volumes:
      - .:/usr/src/app # Share the project source code with the container
    depends_on:
      - db # Wait for the database service to be ready before starting the backend

  db:
    image: postgres:14-alpine # Use the official PostgreSQL image
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=urubu_bondoso
    ports:
      - "5432:5432" # Map port 5432 of the container to port 5432 of the host
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist the database data in a volume

volumes:
  postgres-data: # Define a volume to persist PostgreSQL data